# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: repository # name of the parameter; required
  type: string # data type of the parameter; required


stages:
- stage: Docker
  displayName: Build and Push Docker Image
  jobs:
  - job: Build_Push
    displayName: Build and Push Dockerimage
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'GHCR'  # The name of your Azure Container Registry
        repository: 'viertel97/${{ parameters.repository }}'  # The name of the repository
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: latest,$(Build.BuildNumber)